from datetime import date
from .constants import SQL_TABLES


def get_ddl() -> str:
    today = date.today().isoformat()
    return f"""-- ============================================================
-- FHIR R4 → Databricks Delta Lake Schema
-- Generated by CCDA·AI Platform  {today}
-- ============================================================

CREATE TABLE IF NOT EXISTS fhir_bundles (
  id              BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id       STRING NOT NULL,
  source_file     STRING,
  resource_count  INT,
  loaded_at       TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_patients (
  id                 BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id          STRING,
  source_file        STRING,
  patient_id         STRING,
  active             BOOLEAN,
  mrn                STRING,
  mrn_system         STRING,
  family_name        STRING,
  given_name         STRING,
  prefix             STRING,
  suffix             STRING,
  gender             STRING,
  birth_date         STRING,
  deceased           STRING,
  address_line       STRING,
  city               STRING,
  state              STRING,
  postal_code        STRING,
  country            STRING,
  phone              STRING,
  email              STRING,
  marital_status     STRING,
  race_code          STRING,
  race_display       STRING,
  ethnicity_code     STRING,
  ethnicity_display  STRING,
  language_code      STRING,
  language_preferred BOOLEAN,
  loaded_at          TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_conditions (
  id                   BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id            STRING,
  source_file          STRING,
  condition_id         STRING,
  clinical_status      STRING,
  verification_status  STRING,
  category             STRING,
  severity_code        STRING,
  severity_display     STRING,
  code                 STRING,
  code_system          STRING,
  display              STRING,
  body_site_code       STRING,
  body_site_display    STRING,
  patient_ref          STRING,
  onset_date           STRING,
  abatement_date       STRING,
  recorded_date        STRING,
  recorder_display     STRING,
  note                 STRING,
  loaded_at            TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_medication_requests (
  id                    BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id             STRING,
  source_file           STRING,
  medication_id         STRING,
  status                STRING,
  intent                STRING,
  medication_code       STRING,
  code_system           STRING,
  display               STRING,
  patient_ref           STRING,
  authored_on           STRING,
  validity_period_start STRING,
  validity_period_end   STRING,
  route_code            STRING,
  route_display         STRING,
  dose_value            DOUBLE,
  dose_unit             STRING,
  rate_value            DOUBLE,
  rate_unit             STRING,
  refills               INT,
  reason_code           STRING,
  reason_system         STRING,
  reason_display        STRING,
  requester_display     STRING,
  requester_npi         STRING,
  note                  STRING,
  loaded_at             TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_medication_administrations (
  id                    BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id             STRING,
  source_file           STRING,
  administration_id     STRING,
  status                STRING,
  status_reason_code    STRING,
  status_reason_display STRING,
  medication_code       STRING,
  code_system           STRING,
  display               STRING,
  patient_ref           STRING,
  effective_date        STRING,
  effective_start       STRING,
  effective_end         STRING,
  route_code            STRING,
  route_display         STRING,
  site_code             STRING,
  site_display          STRING,
  dose_value            DOUBLE,
  dose_unit             STRING,
  rate_value            DOUBLE,
  rate_unit             STRING,
  performer_display     STRING,
  performer_npi         STRING,
  reason_code           STRING,
  reason_system         STRING,
  reason_display        STRING,
  note                  STRING,
  loaded_at             TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_allergy_intolerances (
  id               BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id        STRING,
  source_file      STRING,
  allergy_id       STRING,
  patient_ref      STRING,
  code             STRING,
  code_system      STRING,
  display          STRING,
  allergy_type     STRING,
  criticality      STRING,
  clinical_status  STRING,
  loaded_at        TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_observations (
  id                     BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id              STRING,
  source_file            STRING,
  observation_id         STRING,
  status                 STRING,
  category               STRING,
  category_display       STRING,
  code                   STRING,
  code_system            STRING,
  display                STRING,
  patient_ref            STRING,
  effective_date         STRING,
  effective_start        STRING,
  effective_end          STRING,
  value_quantity         DOUBLE,
  value_unit             STRING,
  value_code             STRING,
  value_code_display     STRING,
  value_string           STRING,
  value_range_low        DOUBLE,
  value_range_high       DOUBLE,
  interpretation_code    STRING,
  interpretation_display STRING,
  ref_range_low          DOUBLE,
  ref_range_high         DOUBLE,
  ref_range_text         STRING,
  body_site_code         STRING,
  body_site_display      STRING,
  method_code            STRING,
  method_display         STRING,
  performer_display      STRING,
  performer_npi          STRING,
  note                   STRING,
  loaded_at              TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_encounters (
  id                   BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id            STRING,
  source_file          STRING,
  encounter_id         STRING,
  status               STRING,
  class_code           STRING,
  class_display        STRING,
  type_code            STRING,
  type_system          STRING,
  type_display         STRING,
  priority_code        STRING,
  priority_display     STRING,
  patient_ref          STRING,
  period_start         STRING,
  period_end           STRING,
  reason_code          STRING,
  reason_system        STRING,
  reason_display       STRING,
  diagnosis_code       STRING,
  diagnosis_system     STRING,
  diagnosis_display    STRING,
  participant_display  STRING,
  participant_npi      STRING,
  location_display     STRING,
  loaded_at            TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_procedures (
  id                  BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id           STRING,
  source_file         STRING,
  procedure_id        STRING,
  status              STRING,
  code                STRING,
  code_system         STRING,
  display             STRING,
  patient_ref         STRING,
  performed_date      STRING,
  performed_start     STRING,
  performed_end       STRING,
  body_site_code      STRING,
  body_site_display   STRING,
  method_code         STRING,
  method_display      STRING,
  performer_display   STRING,
  performer_npi       STRING,
  reason_code         STRING,
  reason_system       STRING,
  reason_display      STRING,
  outcome_code        STRING,
  outcome_display     STRING,
  note                STRING,
  loaded_at           TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_immunizations (
  id                    BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id             STRING,
  source_file           STRING,
  immunization_id       STRING,
  status                STRING,
  status_reason_code    STRING,
  status_reason_display STRING,
  vaccine_code          STRING,
  code_system           STRING,
  display               STRING,
  lot_number            STRING,
  manufacturer          STRING,
  route_code            STRING,
  route_display         STRING,
  site_code             STRING,
  site_display          STRING,
  dose_value            DOUBLE,
  dose_unit             STRING,
  patient_ref           STRING,
  occurrence_date       STRING,
  primary_source        BOOLEAN,
  performer_display     STRING,
  performer_npi         STRING,
  loaded_at             TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_diagnostic_reports (
  id                  BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id           STRING,
  source_file         STRING,
  report_id           STRING,
  identifier          STRING,
  identifier_system   STRING,
  status              STRING,
  category_code       STRING,
  category_display    STRING,
  code                STRING,
  code_system         STRING,
  display             STRING,
  patient_ref         STRING,
  effective_date      STRING,
  effective_start     STRING,
  effective_end       STRING,
  issued              STRING,
  encounter_ref       STRING,
  performer_display   STRING,
  performer_npi       STRING,
  result_count        INT,
  conclusion          STRING,
  conclusion_code     STRING,
  conclusion_display  STRING,
  loaded_at           TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_practitioners (
  id                BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id         STRING,
  source_file       STRING,
  practitioner_id   STRING,
  active            BOOLEAN,
  npi               STRING,
  identifier_system STRING,
  family_name       STRING,
  given_name        STRING,
  prefix            STRING,
  suffix            STRING,
  phone             STRING,
  fax               STRING,
  email             STRING,
  address_line      STRING,
  city              STRING,
  state             STRING,
  postal_code       STRING,
  country           STRING,
  qual_code         STRING,
  qual_system       STRING,
  qual_display      STRING,
  loaded_at         TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_organizations (
  id                BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id         STRING,
  source_file       STRING,
  organization_id   STRING,
  active            BOOLEAN,
  npi               STRING,
  identifier_system STRING,
  org_identifier    STRING,
  name              STRING,
  org_type          STRING,
  phone             STRING,
  fax               STRING,
  email             STRING,
  address_line      STRING,
  city              STRING,
  state             STRING,
  postal_code       STRING,
  country           STRING,
  loaded_at         TIMESTAMP DEFAULT current_timestamp()
);

CREATE TABLE IF NOT EXISTS fhir_practitioner_roles (
  id                BIGINT GENERATED ALWAYS AS IDENTITY,
  bundle_id         STRING,
  source_file       STRING,
  role_id           STRING,
  active            BOOLEAN,
  practitioner_ref  STRING,
  organization_ref  STRING,
  role_code         STRING,
  role_display      STRING,
  role_system       STRING,
  specialty_code    STRING,
  specialty_display STRING,
  period_start      STRING,
  period_end        STRING,
  loaded_at         TIMESTAMP DEFAULT current_timestamp()
);
"""

def rows_from_bundle(bundle: dict) -> dict:
    bundle_id = bundle.get("id", "")
    source_file = bundle.get("_meta", {}).get("sourceFile", "unknown")
    counts = bundle.get("_meta", {}).get("counts", {})
    rows: dict[str, list] = {t["name"]: [] for t in SQL_TABLES}

    rows["fhir_bundles"].append({
        "bundle_id": bundle_id,
        "source_file": source_file,
        "resource_count": counts.get("total", len(bundle.get("entry", []))),
    })

    for entry in bundle.get("entry", []):
        r = entry.get("resource", {})
        rt = r.get("resourceType", "")

        if rt == "Patient":
            name0 = (r.get("name") or [{}])[0]
            deceased = r.get("deceasedDateTime") or (
                "true" if r.get("deceasedBoolean") is True else
                ("false" if r.get("deceasedBoolean") is False else None)
            )
            rows["fhir_patients"].append({
                "bundle_id":          bundle_id,
                "source_file":        source_file,
                "patient_id":         r.get("id"),
                "active":             1 if r.get("active") else 0,
                "mrn":                r.get("_mrn"),
                "mrn_system":         r.get("_mrn_system"),
                "family_name":        name0.get("family"),
                "given_name":         " ".join(name0.get("given", [])) or None,
                "prefix":             (name0.get("prefix") or [None])[0],
                "suffix":             (name0.get("suffix") or [None])[0],
                "gender":             r.get("gender"),
                "birth_date":         r.get("birthDate"),
                "deceased":           deceased,
                "address_line":       r.get("_address_line"),
                "city":               r.get("_city"),
                "state":              r.get("_state"),
                "postal_code":        r.get("_postal_code"),
                "country":            r.get("_country"),
                "phone":              r.get("_phone"),
                "email":              r.get("_email"),
                "marital_status":     r.get("maritalStatus", {}).get("text") if r.get("maritalStatus") else None,
                "race_code":          r.get("_race_code"),
                "race_display":       r.get("_race_display"),
                "ethnicity_code":     r.get("_ethnicity_code"),
                "ethnicity_display":  r.get("_ethnicity_display"),
                "language_code":      r.get("_lang_code"),
                "language_preferred": r.get("_lang_preferred"),
            })

        elif rt == "Condition":
            coding0  = (r.get("code", {}).get("coding") or [{}])[0]
            cs_c     = (r.get("clinicalStatus", {}).get("coding") or [{}])[0]
            vs_c     = (r.get("verificationStatus", {}).get("coding") or [{}])[0]
            cat_c    = ((r.get("category") or [{}])[0].get("coding") or [{}])[0]
            sev      = r.get("severity") or {}
            sev_c    = (sev.get("coding") or [{}])[0]
            bs0      = (r.get("bodySite") or [{}])[0]
            bs_c     = (bs0.get("coding") or [{}])[0]
            recorder = r.get("recorder") or {}
            note0    = (r.get("note") or [{}])[0]
            rows["fhir_conditions"].append({
                "bundle_id":          bundle_id,
                "source_file":        source_file,
                "condition_id":       r.get("id"),
                "clinical_status":    cs_c.get("code"),
                "verification_status": vs_c.get("code"),
                "category":           cat_c.get("code"),
                "severity_code":      sev_c.get("code"),
                "severity_display":   sev.get("text") or sev_c.get("display"),
                "code":               coding0.get("code"),
                "code_system":        coding0.get("system"),
                "display":            r.get("code", {}).get("text") or coding0.get("display"),
                "body_site_code":     bs_c.get("code"),
                "body_site_display":  bs_c.get("display"),
                "patient_ref":        (r.get("subject", {}).get("reference") or "").replace("Patient/", "") or None,
                "onset_date":         r.get("onsetDateTime"),
                "abatement_date":     r.get("abatementDateTime"),
                "recorded_date":      r.get("recordedDate"),
                "recorder_display":   recorder.get("display"),
                "note":               note0.get("text"),
            })

        elif rt == "MedicationRequest":
            mc     = r.get("medicationCodeableConcept") or {}
            coding0= (mc.get("coding") or [{}])[0]
            di0    = (r.get("dosageInstruction") or [{}])[0]
            dar0   = (di0.get("doseAndRate") or [{}])[0]
            dq     = dar0.get("doseQuantity") or {}
            rq     = dar0.get("rateQuantity") or {}
            route  = di0.get("route") or {}
            route_c= (route.get("coding") or [{}])[0]
            req    = r.get("requester") or {}
            rc0    = (r.get("reasonCode") or [{}])[0]
            rcc    = (rc0.get("coding") or [{}])[0]
            dr     = r.get("dispenseRequest") or {}
            vp     = dr.get("validityPeriod") or {}
            note0  = (r.get("note") or [{}])[0]
            rows["fhir_medication_requests"].append({
                "bundle_id":             bundle_id,
                "source_file":           source_file,
                "medication_id":         r.get("id"),
                "status":                r.get("status"),
                "intent":                r.get("intent"),
                "medication_code":       coding0.get("code"),
                "code_system":           coding0.get("system"),
                "display":               mc.get("text") or coding0.get("display"),
                "patient_ref":           (r.get("subject", {}).get("reference") or "").replace("Patient/", "") or None,
                "authored_on":           r.get("authoredOn"),
                "validity_period_start": vp.get("start"),
                "validity_period_end":   vp.get("end"),
                "route_code":            route_c.get("code"),
                "route_display":         route.get("text") or route_c.get("display"),
                "dose_value":            dq.get("value"),
                "dose_unit":             dq.get("unit"),
                "rate_value":            rq.get("value"),
                "rate_unit":             rq.get("unit"),
                "refills":               dr.get("numberOfRepeatsAllowed"),
                "reason_code":           rcc.get("code"),
                "reason_system":         rcc.get("system"),
                "reason_display":        rc0.get("text") or rcc.get("display"),
                "requester_display":     req.get("display"),
                "requester_npi":         req.get("_npi"),
                "note":                  note0.get("text"),
            })

        elif rt == "MedicationAdministration":
            mc      = r.get("medicationCodeableConcept") or {}
            mcc     = (mc.get("coding") or [{}])[0]
            ep      = r.get("effectivePeriod") or {}
            perf0   = (r.get("performer") or [{}])[0]
            actor   = perf0.get("actor") or {}
            rc0     = (r.get("reasonCode") or [{}])[0]
            rcc     = (rc0.get("coding") or [{}])[0]
            sr0     = (r.get("statusReason") or [{}])[0]
            src0    = (sr0.get("coding") or [{}])[0]
            dosage  = r.get("dosage") or {}
            dq      = dosage.get("dose") or {}
            rq      = dosage.get("rateQuantity") or {}
            route   = dosage.get("route") or {}
            rtc     = (route.get("coding") or [{}])[0]
            site    = dosage.get("site") or {}
            stc     = (site.get("coding") or [{}])[0]
            note0   = (r.get("note") or [{}])[0]
            rows["fhir_medication_administrations"].append({
                "bundle_id":             bundle_id,
                "source_file":           source_file,
                "administration_id":     r.get("id"),
                "status":                r.get("status"),
                "status_reason_code":    src0.get("code"),
                "status_reason_display": sr0.get("text") or src0.get("display"),
                "medication_code":       mcc.get("code"),
                "code_system":           mcc.get("system"),
                "display":               mc.get("text") or mcc.get("display"),
                "patient_ref":           (r.get("subject", {}).get("reference") or "").replace("Patient/", "") or None,
                "effective_date":        r.get("effectiveDateTime"),
                "effective_start":       ep.get("start"),
                "effective_end":         ep.get("end"),
                "route_code":            rtc.get("code"),
                "route_display":         route.get("text") or rtc.get("display"),
                "site_code":             stc.get("code"),
                "site_display":          site.get("text") or stc.get("display"),
                "dose_value":            dq.get("value"),
                "dose_unit":             dq.get("unit"),
                "rate_value":            rq.get("value"),
                "rate_unit":             rq.get("unit"),
                "performer_display":     actor.get("display"),
                "performer_npi":         actor.get("_npi"),
                "reason_code":           rcc.get("code"),
                "reason_system":         rcc.get("system"),
                "reason_display":        rc0.get("text") or rcc.get("display"),
                "note":                  note0.get("text"),
            })

        elif rt == "AllergyIntolerance":
            coding0 = (r.get("code", {}).get("coding") or [{}])[0]
            cs_status = (r.get("clinicalStatus", {}).get("coding") or [{}])[0]
            rows["fhir_allergy_intolerances"].append({
                "bundle_id": bundle_id,
                "source_file": source_file,
                "allergy_id": r.get("id"),
                "patient_ref": (r.get("patient", {}).get("reference") or "").replace("Patient/", "") or None,
                "code": coding0.get("code"),
                "code_system": coding0.get("system"),
                "display": r.get("code", {}).get("text") or coding0.get("display"),
                "allergy_type": r.get("type"),
                "criticality": r.get("criticality"),
                "clinical_status": cs_status.get("code"),
            })

        elif rt == "Observation":
            coding0   = (r.get("code", {}).get("coding") or [{}])[0]
            cat0      = (r.get("category") or [{}])[0]
            cat_c     = (cat0.get("coding") or [{}])[0]
            vq        = r.get("valueQuantity") or {}
            vr        = r.get("valueRange") or {}
            vcc       = r.get("valueCodeableConcept") or {}
            vcc_c     = (vcc.get("coding") or [{}])[0]
            interp0   = (r.get("interpretation") or [{}])[0]
            interp_c  = (interp0.get("coding") or [{}])[0]
            rr0       = (r.get("referenceRange") or [{}])[0]
            rr_low    = rr0.get("low") or {}
            rr_high   = rr0.get("high") or {}
            bs        = r.get("bodySite") or {}
            bs_c      = (bs.get("coding") or [{}])[0]
            meth      = r.get("method") or {}
            meth_c    = (meth.get("coding") or [{}])[0]
            perf0     = (r.get("performer") or [{}])[0]
            ep        = r.get("effectivePeriod") or {}
            note0     = (r.get("note") or [{}])[0]
            rows["fhir_observations"].append({
                "bundle_id":            bundle_id,
                "source_file":          source_file,
                "observation_id":       r.get("id"),
                "status":               r.get("status"),
                "category":             cat_c.get("code"),
                "category_display":     cat0.get("text") or cat_c.get("display"),
                "code":                 coding0.get("code"),
                "code_system":          coding0.get("system"),
                "display":              r.get("code", {}).get("text") or coding0.get("display"),
                "patient_ref":          (r.get("subject", {}).get("reference") or "").replace("Patient/", "") or None,
                "effective_date":       r.get("effectiveDateTime"),
                "effective_start":      ep.get("start"),
                "effective_end":        ep.get("end"),
                "value_quantity":       vq.get("value"),
                "value_unit":           vq.get("unit"),
                "value_code":           vcc_c.get("code"),
                "value_code_display":   vcc.get("text") or vcc_c.get("display"),
                "value_string":         r.get("valueString"),
                "value_range_low":      (vr.get("low") or {}).get("value"),
                "value_range_high":     (vr.get("high") or {}).get("value"),
                "interpretation_code":  interp_c.get("code"),
                "interpretation_display": interp0.get("text") or interp_c.get("display"),
                "ref_range_low":        rr_low.get("value"),
                "ref_range_high":       rr_high.get("value"),
                "ref_range_text":       rr0.get("text"),
                "body_site_code":       bs_c.get("code"),
                "body_site_display":    bs.get("text") or bs_c.get("display"),
                "method_code":          meth_c.get("code"),
                "method_display":       meth.get("text") or meth_c.get("display"),
                "performer_display":    perf0.get("display"),
                "performer_npi":        perf0.get("_npi"),
                "note":                 note0.get("text"),
            })

        elif rt == "Encounter":
            period   = r.get("period") or {}
            cls      = r.get("class") or {}
            type0    = (r.get("type") or [{}])[0]
            type_c   = (type0.get("coding") or [{}])[0]
            pri      = r.get("priority") or {}
            pri_c    = (pri.get("coding") or [{}])[0]
            diag0    = (r.get("diagnosis") or [{}])[0]
            reason0  = (r.get("reasonCode") or [{}])[0]
            reason_c = (reason0.get("coding") or [{}])[0]
            part0    = (r.get("participant") or [{}])[0]
            loc0     = (r.get("location") or [{}])[0]
            rows["fhir_encounters"].append({
                "bundle_id":           bundle_id,
                "source_file":         source_file,
                "encounter_id":        r.get("id"),
                "status":              r.get("status"),
                "class_code":          cls.get("code"),
                "class_display":       cls.get("display"),
                "type_code":           type_c.get("code"),
                "type_system":         type_c.get("system"),
                "type_display":        type0.get("text") or type_c.get("display"),
                "priority_code":       pri_c.get("code"),
                "priority_display":    pri.get("text") or pri_c.get("display"),
                "patient_ref":         (r.get("subject", {}).get("reference") or "").replace("Patient/", "") or None,
                "period_start":        period.get("start"),
                "period_end":          period.get("end"),
                "reason_code":         reason_c.get("code"),
                "reason_system":       reason_c.get("system"),
                "reason_display":      reason0.get("text") or reason_c.get("display"),
                "diagnosis_code":      diag0.get("_code"),
                "diagnosis_system":    diag0.get("_system"),
                "diagnosis_display":   (diag0.get("condition") or {}).get("display"),
                "participant_display": (part0.get("individual") or {}).get("display"),
                "participant_npi":     part0.get("_npi"),
                "location_display":    (loc0.get("location") or {}).get("display"),
            })

        elif rt == "Procedure":
            coding0  = (r.get("code", {}).get("coding") or [{}])[0]
            pp       = r.get("performedPeriod") or {}
            perf0    = (r.get("performer") or [{}])[0]
            actor    = perf0.get("actor") or {}
            rc0      = (r.get("reasonCode") or [{}])[0]
            rcc      = (rc0.get("coding") or [{}])[0]
            oc       = r.get("outcome") or {}
            oc_c     = (oc.get("coding") or [{}])[0]
            bs0      = (r.get("bodySite") or [{}])[0]
            bs_c     = (bs0.get("coding") or [{}])[0]
            meth     = r.get("method") or {}
            meth_c   = (meth.get("coding") or [{}])[0]
            note0    = (r.get("note") or [{}])[0]
            rows["fhir_procedures"].append({
                "bundle_id":        bundle_id,
                "source_file":      source_file,
                "procedure_id":     r.get("id"),
                "status":           r.get("status"),
                "code":             coding0.get("code"),
                "code_system":      coding0.get("system"),
                "display":          r.get("code", {}).get("text") or coding0.get("display"),
                "patient_ref":      (r.get("subject", {}).get("reference") or "").replace("Patient/", "") or None,
                "performed_date":   r.get("performedDateTime"),
                "performed_start":  pp.get("start"),
                "performed_end":    pp.get("end"),
                "body_site_code":   bs_c.get("code"),
                "body_site_display": bs0.get("text") or bs_c.get("display"),
                "method_code":      meth_c.get("code"),
                "method_display":   meth.get("text") or meth_c.get("display"),
                "performer_display": actor.get("display"),
                "performer_npi":    actor.get("_npi"),
                "reason_code":      rcc.get("code"),
                "reason_system":    rcc.get("system"),
                "reason_display":   rc0.get("text") or rcc.get("display"),
                "outcome_code":     oc_c.get("code"),
                "outcome_display":  oc.get("text") or oc_c.get("display"),
                "note":             note0.get("text"),
            })

        elif rt == "Immunization":
            vc       = r.get("vaccineCode") or {}
            coding0  = (vc.get("coding") or [{}])[0]
            sr       = r.get("statusReason") or {}
            sr_c     = (sr.get("coding") or [{}])[0]
            route    = r.get("route") or {}
            route_c  = (route.get("coding") or [{}])[0]
            site     = r.get("site") or {}
            site_c   = (site.get("coding") or [{}])[0]
            dq       = r.get("doseQuantity") or {}
            mfr      = r.get("manufacturer") or {}
            perf0    = (r.get("performer") or [{}])[0]
            rows["fhir_immunizations"].append({
                "bundle_id":             bundle_id,
                "source_file":           source_file,
                "immunization_id":       r.get("id"),
                "status":                r.get("status"),
                "status_reason_code":    sr_c.get("code"),
                "status_reason_display": sr.get("text") or sr_c.get("display"),
                "vaccine_code":          coding0.get("code"),
                "code_system":           coding0.get("system"),
                "display":               vc.get("text") or coding0.get("display"),
                "lot_number":            r.get("lotNumber"),
                "manufacturer":          mfr.get("display"),
                "route_code":            route_c.get("code"),
                "route_display":         route.get("text") or route_c.get("display"),
                "site_code":             site_c.get("code"),
                "site_display":          site.get("text") or site_c.get("display"),
                "dose_value":            dq.get("value"),
                "dose_unit":             dq.get("unit"),
                "patient_ref":           (r.get("patient", {}).get("reference") or "").replace("Patient/", "") or None,
                "occurrence_date":       r.get("occurrenceDateTime"),
                "primary_source":        1 if r.get("primarySource") else 0,
                "performer_display":     (perf0.get("actor") or {}).get("display"),
                "performer_npi":         perf0.get("_npi"),
            })

        elif rt == "DiagnosticReport":
            cat0    = (r.get("category") or [{}])[0]
            cat_c   = (cat0.get("coding") or [{}])[0]
            coding0 = (r.get("code", {}).get("coding") or [{}])[0]
            ep      = r.get("effectivePeriod") or {}
            perf0   = (r.get("performer") or [{}])[0]
            cc0     = (r.get("conclusionCode") or [{}])[0]
            cc_c    = (cc0.get("coding") or [{}])[0]
            rows["fhir_diagnostic_reports"].append({
                "bundle_id":          bundle_id,
                "source_file":        source_file,
                "report_id":          r.get("id"),
                "identifier":         r.get("_identifier"),
                "identifier_system":  r.get("_identifier_system"),
                "status":             r.get("status"),
                "category_code":      cat_c.get("code"),
                "category_display":   cat0.get("text") or cat_c.get("display"),
                "code":               coding0.get("code"),
                "code_system":        coding0.get("system"),
                "display":            r.get("code", {}).get("text") or coding0.get("display"),
                "patient_ref":        (r.get("subject", {}).get("reference") or "").replace("Patient/", "") or None,
                "effective_date":     r.get("effectiveDateTime"),
                "effective_start":    ep.get("start"),
                "effective_end":      ep.get("end"),
                "issued":             r.get("issued"),
                "encounter_ref":      (r.get("encounter") or {}).get("reference", "").replace("Encounter/", "") or None,
                "performer_display":  perf0.get("display"),
                "performer_npi":      r.get("_performer_npi"),
                "result_count":       r.get("_result_count"),
                "conclusion":         r.get("conclusion"),
                "conclusion_code":    r.get("_conclusion_code"),
                "conclusion_display": r.get("_conclusion_display"),
            })

        elif rt == "Practitioner":
            name0   = (r.get("name") or [{}])[0]
            id0     = (r.get("identifier") or [{}])[0]
            tel     = r.get("telecom") or []
            addr0   = (r.get("address") or [{}])[0]
            qual0   = (r.get("qualification") or [{}])[0]
            qual_c  = (qual0.get("code", {}).get("coding") or [{}])[0] if qual0 else {}
            phone   = next((t["value"] for t in tel if t.get("system") == "phone"), None)
            fax     = next((t["value"] for t in tel if t.get("system") == "fax"),   None)
            email   = next((t["value"] for t in tel if t.get("system") == "email"), None)
            npi_val = id0.get("value")
            npi_sys = id0.get("system")
            rows["fhir_practitioners"].append({
                "bundle_id":         bundle_id,
                "source_file":       source_file,
                "practitioner_id":   r.get("id"),
                "active":            1 if r.get("active") else 0,
                "npi":               npi_val if npi_sys and "us-npi" in npi_sys else None,
                "identifier_system": npi_sys,
                "family_name":       name0.get("family"),
                "given_name":        " ".join(name0.get("given", [])) or None,
                "prefix":            " ".join(name0.get("prefix", [])) or None,
                "suffix":            " ".join(name0.get("suffix", [])) or None,
                "phone":             phone,
                "fax":               fax,
                "email":             email,
                "address_line":      (addr0.get("line") or [None])[0],
                "city":              addr0.get("city"),
                "state":             addr0.get("state"),
                "postal_code":       addr0.get("postalCode"),
                "country":           addr0.get("country"),
                "qual_code":         qual_c.get("code"),
                "qual_system":       qual_c.get("system"),
                "qual_display":      qual_c.get("display"),
            })

        elif rt == "Organization":
            id0     = (r.get("identifier") or [{}])[0]
            tel     = r.get("telecom") or []
            addr0   = (r.get("address") or [{}])[0]
            type0   = ((r.get("type") or [{}])[0].get("coding") or [{}])[0]
            phone   = next((t["value"] for t in tel if t.get("system") == "phone"), None)
            fax     = next((t["value"] for t in tel if t.get("system") == "fax"),   None)
            email   = next((t["value"] for t in tel if t.get("system") == "email"), None)
            id_val  = id0.get("value")
            id_sys  = id0.get("system")
            rows["fhir_organizations"].append({
                "bundle_id":         bundle_id,
                "source_file":       source_file,
                "organization_id":   r.get("id"),
                "active":            1 if r.get("active") else 0,
                "npi":               id_val if id_sys and "us-npi" in id_sys else None,
                "identifier_system": id_sys,
                "org_identifier":    id_val,
                "name":              r.get("name"),
                "org_type":          type0.get("display") or type0.get("code"),
                "phone":             phone,
                "fax":               fax,
                "email":             email,
                "address_line":      (addr0.get("line") or [None])[0],
                "city":              addr0.get("city"),
                "state":             addr0.get("state"),
                "postal_code":       addr0.get("postalCode"),
                "country":           addr0.get("country"),
            })

        elif rt == "PractitionerRole":
            role_c  = ((r.get("code") or [{}])[0].get("coding") or [{}])[0]
            spec_c  = ((r.get("specialty") or [{}])[0].get("coding") or [{}])[0]
            period  = r.get("period") or {}
            rows["fhir_practitioner_roles"].append({
                "bundle_id":         bundle_id,
                "source_file":       source_file,
                "role_id":           r.get("id"),
                "active":            1 if r.get("active") else 0,
                "practitioner_ref":  (r.get("practitioner", {}).get("reference") or "").replace("Practitioner/", "") or None,
                "organization_ref":  (r.get("organization",  {}).get("reference") or "").replace("Organization/",  "") or None,
                "role_code":         role_c.get("code"),
                "role_display":      role_c.get("display"),
                "role_system":       role_c.get("system"),
                "specialty_code":    spec_c.get("code"),
                "specialty_display": spec_c.get("display"),
                "period_start":      period.get("start"),
                "period_end":        period.get("end"),
            })

    return rows


def create_tables(conn) -> dict:
    ddl = get_ddl()
    cursor = conn.cursor()
    try:
        statements = [s.strip() for s in ddl.split(";") if s.strip()]
        for stmt in statements:
            if stmt.upper().startswith("CREATE"):
                try:
                    cursor.execute(stmt)
                except Exception:
                    pass
        return {"success": True, "message": "All FHIR Delta tables created (or already exist)."}
    except Exception as e:
        return {"success": False, "message": str(e)}
    finally:
        cursor.close()


def load_bundle(conn, bundle: dict) -> dict:
    all_rows = rows_from_bundle(bundle)
    cursor = conn.cursor()
    inserted = 0
    try:
        for table_name, rows in all_rows.items():
            for row in rows:
                cols = list(row.keys())
                placeholders = ", ".join(["%s" for _ in cols])
                values = [row[c] for c in cols]
                sql = f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES ({placeholders})"
                cursor.execute(sql, values)
                inserted += 1
        return {"success": True, "rows_inserted": inserted}
    except Exception as e:
        return {"success": False, "message": str(e), "rows_inserted": 0}
    finally:
        cursor.close()


def truncate_all(conn) -> dict:
    cursor = conn.cursor()
    try:
        for t in reversed(SQL_TABLES):
            try:
                cursor.execute(f"TRUNCATE TABLE {t['name']}")
            except Exception:
                pass
        return {"success": True}
    except Exception as e:
        return {"success": False, "message": str(e)}
    finally:
        cursor.close()


def get_table_counts(conn) -> dict:
    cursor = conn.cursor()
    counts = {}
    for t in SQL_TABLES:
        try:
            cursor.execute(f"SELECT COUNT(*) FROM {t['name']}")
            row = cursor.fetchone()
            counts[t["name"]] = row[0] if row else 0
        except Exception:
            counts[t["name"]] = None
    cursor.close()
    return counts
